---
- name: Ensure ssl directory exist
  file:
    path: "{{ mongodb_net_ssl_location }}"
    state: directory
    owner: "mongod"
    group: "mongod"
    mode: 0755
    follow: true
  when: mongodb_net_ssl

- name: Create log dir if missing
  file:
    state: directory
    dest: "{{ mongodb_systemlog_path | dirname }}"
    owner: "mongod"
    group: "mongod"
    mode: 0755
  when: mongodb_systemlog_destination == "file"

- name: Ensure dbpath directory
  file:
    path: "{{ mongodb_storage_dbpath }}"
    state: directory
    owner: "mongod"
    group: "mongod"
    mode: 0755
    follow: yes

- name: Copy security keyfile
  copy:
    dest: "{{ mongodb_security_keyfile_location }}"
    src: "{{ mongodb_security_keyfile }}"
    owner: "mongod"
    group: "root"
    mode: 0600
  when:
    - mongodb_net_ssl
    - mongodb_security_keyfile is defined
    - mongodb_replication_replset
    - mongodb_security_authorization == 'enabled'
    - mongodb_net_ssl_clusterfile is not defined

- name: Copy ssl keyfile
  copy:
    dest: "{{ mongodb_net_ssl_keyfile_location }}"
    src: "{{ mongodb_net_ssl_keyfile }}"
    owner: "mongod"
    group: "root"
    mode: 0600
  when:
    - mongodb_net_ssl_keyfile is defined
    - mongodb_net_ssl

- name: Copy ssl CA file
  copy:
    dest: "{{ mongodb_net_ssl_cafile_location }}"
    src: "{{ mongodb_net_ssl_cafile }}"
    owner: "mongod"
    group: "root"
    mode: 0600
  when:
    - mongodb_net_ssl_cafile is defined
    - mongodb_net_ssl

- name: Copy ssl cluster file
  copy:
    dest: "{{ mongodb_net_ssl_clusterfile_location }}"
    src: "{{ mongodb_net_ssl_clusterfile }}"
    owner: "mongod"
    group: "root"
    mode: 0600
  when:
    - mongodb_net_ssl_clusterfile is defined
    - mongodb_net_ssl

- name: Configure mongodb
  template:
    src: mongod.conf.j2
    dest: "/etc/mongod.conf"
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongod
